### ISSUE TITLE
HTTP Status: 500 Internal Server Error rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup currencyservice on 10.96.0.10:53: read udp 10.244.43.6:45880->10.96.0.10:53: i/o timeout"

### ISSUE THREAD

**Issue by Iceforestik** [GoogleCloudPlatform/microservices-demo#1042]
Hello, I get this error, all the pods are working except adservice
![изображение](https://user-images.githubusercontent.com/47591939/189538014-1673e0bd-7790-42b0-9b44-0369ec9995c7.png)
ingress
```
apiVersion: [networking.k8s.io/v1](http://networking.k8s.io/v1)
kind: Ingress
metadata:
 name: ingress
 annotations:
   [nginx.ingress.kubernetes.io/rewrite-target](http://nginx.ingress.kubernetes.io/rewrite-target): /
spec:
 ingressClassName: nginx
 rules:
   - http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: frontend
               port:
                 number: 80
```
pods and svc,ingress

![изображение](https://user-images.githubusercontent.com/47591939/189538172-28c8f7ee-329f-41a6-a1fd-6828f752932c.png)

how to solve it?

**Comment by ahrarmonsur** [comment]
@NimJay please advise, thank you.

**Comment by NimJay** [comment]
Hi @Iceforestik,
Thank you reporting this issue!
1. I see that you are using an `Ingress` object (and I assume a `Service` that _not_ of `type: LoadBalancer`). In other words, you've modified the default [`kubernetes-manifests`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/release/kubernetes-manifests.yaml) of Online Boutique. Could you please share all modifications you've made?
2. What type of Kubernetes cluster are you using? A local Kind cluster? A local minikube cluster? GKE?
3. Could you please share the logs from your `adservice` Pod? In other words, please run (and share the output of) `kubectl logs <NAME OF YOUR adservice POD>`. You can find the name of your `adservice` Pod using `kubectl get pods`.

**Comment by Iceforestik** [comment]
Hi @NimJay 
thank you for your interest in my question
it turned out to be my mistake, I had problems with calico bgp +  I had to rewrite two samples from currencyservice + fix my firewall( opened several important ports) the most interesting thing is that after that, adservice earned
```
livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 20
        name: server
        ports:
        - containerPort: 7000
          name: grpc
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
```
