### ISSUE TITLE
Move cloud-ops-sandbox kustomization configuration to CloudOps Sandbox repo

### ISSUE THREAD

**Issue by minherz** [GoogleCloudPlatform/microservices-demo#1571]
### Describe request or inquiry 

PR #1566 added the kustomization config that deploys Online Boutique using the configuration that Sandbox uses. It makes sense to host this kustomization config in the Sandbox [repo] instead of the one of Online Boutique.

The possible setup that "fixes" Online Boutique version can look like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/GoogleCloudPlatform/microservices-demo/kustomize/base?ref=release/v0.5.1
components:
- github.com/GoogleCloudPlatform/microservices-demo/kustomize/components/google-cloud-operations?ref=release/v0.5.1
```

### What purpose/environment will this feature serve? 

This change will let to avoid misuse of the Online Boutique collection of kustomizations as well as will remove the reversed dependency between Online Boutique and Sandbox.

[repo]: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox
