### ISSUE TITLE
Frontent not reachable behind Ingress

### ISSUE THREAD

**Issue by amrap030** [GoogleCloudPlatform/microservices-demo#1872]
### Describe the bug 
I tried to deploy the Online Boutique in my Kubernetes Cluster, but somehow the frontend is not reachable from my Browser behind a Traefik Ingress. It shows a 404 Error.

### To Reproduce 
1. Successfully create Traefik Ingress on Kubernetes Cluster
2. Install Online Boutique via Helm

```
helm upgrade onlineboutique oci://us-docker.pkg.dev/online-boutique-ci/charts/onlineboutique --install --create-namespace -n demo
```

3. Patch frontend-external service to get ClusterIP

```
kubectl patch svc frontend-external -n demo -p '{"spec": {"type": "ClusterIP"}}'
```

4. Create Ingress

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: acme
  name: jupyter-ingress
spec:
  rules:
  - host: <HOST>
    http:
      paths:
      - path: /demo
        pathType: Prefix
        backend:
          service:
            name: frontend-external # frontend also doesn't work
            port:
              number: 80
  tls:
  - hosts:
    - <HOST>
    secretName: traefik-tls-secret
```

6. Add Ingress to Namespace

```
kubectl -n demo apply -f demo-ingress.yaml
```

For any other application this approach works. Do I miss some configuration?

### Environment 
- OS: Openstack
- Kubernetes distribution, version: Charmed Kubernetes v1.27.3 on Openstack
