### ISSUE TITLE
ENABLE_STATS doesn't do anything

### ISSUE THREAD

**Issue by scarolan** [GoogleCloudPlatform/microservices-demo#2399]
The README suggests ENABLE_STATS to have the app export metrics to OTLP.  This environment variable doesn't seem to do anything, I was unable to find any mentions of it in the go code.  Was this something that was intended to be implemented but never completed?

https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/kustomize/components/google-cloud-operations/README.md#changes

When enabling this kustomize module, most services will be patched with a configuration similar to the following:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  template:
    spec:
      containers:
        - name: server
          env:
          - name: COLLECTOR_SERVICE_ADDR
            value: "opentelemetrycollector:4317"
          - name: ENABLE_STATS
            value: "1"
          - name: ENABLE_TRACING
            value: "1"
```
