### ISSUE TITLE
How to change Istio Ingress default location ? 

### ISSUE THREAD

**Issue by yogeek** [GoogleCloudPlatform/microservices-demo#253]
Hello,

By default, with the deployment on an istio-installed cluster, the frontend is available on :
`http://$INGRESS_HOST`.
I would like to have the frontend available under `http://$INGRESS_HOST/microdemo` so I changed the VirtualService :
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
spec:
  hosts:
  - "*"
  gateways:
  - frontend-gateway
  http:
  - match:
    - uri:
        prefix: "/microdemo"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: frontend
        port:
          number: 80
```
As a result, the root page of the application is avaiblable at `http://$INGRESS_HOST/microdemo` but the other pages (when I click on the cart for example) are not found because (the path is wrong)

Is it possible to change the root context of the web app for this to work correctly under another path than "/" please ?
