### ISSUE TITLE
Remove the "missing version" warnings in istio.

### ISSUE THREAD

**Issue by philippehenin** [GoogleCloudPlatform/microservices-demo#2757]
### Write down your inquiry 

I used your great “microservices-demo” to show Istio maps and functionalities.

I had warnings on "missing version" in the label app for the file release/kubernetes-manifests.yaml :

As an example, I added this

```
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
    version: "1"
```

There is the complete “corrected” file.

Please have no hesitation to close if not relevant.

https://github.com/user-attachments/files/17217269/kubernetes-manifests.yaml.txt
