### ISSUE TITLE
K8S attributes as process tags in tracing data

### ISSUE THREAD

**Issue by vsrakesh** [GoogleCloudPlatform/microservices-demo#570]
This issue is related to OpenCensus support in this project

**Issue Description**
It seems that K8S attributes (namespace, pod-name) are not added as process tags when exporting data to jaeger collector. I hope this is configurable somehow, but I have had no luck in figuring this out. Basically, I'm trying to add HOSTNAME (podName) and NAMESPACE as process tags in tracing span data. My environment is a standalone k8s cluster.

I had tried configuring predefined environment variables as mentioned as a workaround in https://github.com/census-instrumentation/opencensus-python/issues/796, but that does not seem to work either.

Following is the configuration I had tried for adservice
```
env:
- name: KUBERNETES_SERVICE_HOST
  value: "test-cluster"
- name: JAEGER_SERVICE_ADDR
  value: "jaeger-collector.observability.svc.cluster.local:14268"
- name: HOSTNAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
```

I do not see any additional tags in the span data output - here is how it is currently
```
processes: {
	p1: {
		serviceName: "productcatalogservice",
		tags: [ ]
	},
	p2: {
		serviceName: "frontend",
		tags: [ ]
	},
	p3: {
		serviceName: "adservice",
		tags: [ ]
	}
}
```

I might be missing the configuration needed to get this info, however not having much luck figuring it out. Any pointers or documents would be of great help to get this working.
